// ============================================================================
//  weather_sdk.h  —  WEATHER / SKY / ATMOSPHERE SDK for THE HOBBIT (2003) PC build
//  Entropy engine, MSVC, 32-bit (Meridian.exe, preferred base 0x00400000, ASLR off).
//
//  Reverse-engineered modding / trainer SDK. All addresses are absolute PC
//  virtual addresses; resolve them at runtime with meridian::rebase(0xADDR),
//  which applies the current module-base delta vs the analyzed image base.
//
//  This subsystem is the engine's environmental-atmosphere layer:
//    * weather_mgr  — global singleton (g_WeatherMgr) that owns the live weather
//                     state. Per frame OnAdvanceLogic ramps/fades the rain & storm
//                     intensity, advances the particle-weather system, recomputes
//                     a storm AABB around the camera, and lets UI "Storm_" marker
//                     windows seed localized lightning storms. PreSceneRender (run
//                     each frame from render_mgr::Render) strobes the lightning
//                     flash light, and Render submits the storm volumes. Lightning
//                     bolts are recursive fractal "forks" (primary + secondary
//                     pools) generated by TriggerLightningChain.
//    * skybox       — sky-dome object (derives from rigid_instance). Renders first
//                     as the background, scrolls/animates via AnimSpeed +
//                     OffsetScale, and is forced non-occluding / non-colliding.
//    * fog_plane    — planar/distance fog quad (derives from wall). Four corner
//                     vertices + up to N animated UV-scrolling texture layers
//                     drawn in RenderCustom; OnAdvanceLogic advances the UV phase.
//
//  Field offsets are CONSOLIDATED from the per-chunk analysis (weather__00.json)
//  and the decompiled bodies. Offsets marked "?" are lower confidence. Only well-
//  evidenced fields are named; the rest is explicit byte padding so named members
//  land at their true byte offsets. These structs are NOT meant to be
//  instantiated — only reinterpret_cast onto a live engine object (the
//  g_WeatherMgr singleton, or a skybox/fog_plane slot from obj_mgr).
//
//  ---- USAGE / RECIPE ------------------------------------------------------
//    using namespace weather_sdk;
//
//    // Grab the live weather manager singleton (engine global g_WeatherMgr @ 0x00771B70):
//    WeatherMgr* wm = GetWeatherMgr();
//
//    // Force heavy rain (enable flag + fade seconds). NOTE: call on the GAME's main
//    // thread, while a level is loaded (ideally outdoors) — it loads RainOutdoorLoop
//    // and ramps a sub-object that only exists after the level's weather_mgr::Init.
//    fn::WeatherMgr_EnableRain(wm, 1, 1.0f);   // 1 = on, 0 = off ; 1.0f = fade time
//    // Read / poke the rain intensity directly:
//    wm->stormIntensity = 0.85f;
//
//    // Trigger a localized lightning storm at a point (center, RGBA tint):
//    vector3 where = { x, y, z };
//    uint8_t tint[4] = { 0xff, 0xb4, 0xe6, 0xff };   // R,G,B,A
//    fn::WeatherMgr_EnableStorm(wm, &where, tint);   // plays "LightningCrack"
//
//    // Fire a single lightning bolt between two points (5-arg overload):
//    vector3 a = { ax, ay, az }, b = { bx, by, bz };
//    int forkIdx = fn::WeatherMgr_TriggerLightningChain(wm, a, b, 1.0f, /*branchy*/1, 0);
//
//    // Disable all weather (frees fork pools, stops particle weather):
//    fn::WeatherMgr_Kill(wm);
//
//    // Force a sky preset on a skybox slot (editor-style):
//    Skybox* sky = reinterpret_cast<Skybox*>(skySlotPtr);
//    sky->animSpeed   = 0.0f;                         // freeze sky scroll
//    sky->offsetScale = vector3{ 1.0f, 1.0f, 1.0f };  // dome offset scaling
//
//    // Disable a fog plane (collapse its quad / clear textures): cast to FogPlane,
//    // null the texture handles, or just hide the owning object via the engine.
//
//  __thiscall wrappers take the object pointer as the FIRST argument; the static
//  object factories (SkyboxCreator/FogPlaneCreator) are __cdecl. Methods that take
//  an INCOMPLETE engine type BY VALUE, or return a large aggregate via hidden sret
//  (GetProperty), expose an address accessor (*_at) with the raw signature in a
//  comment instead of a typed wrapper. vector3/radian3/bbox are complete
//  (meridian_types.h) so their by-value signatures are ABI-safe.
//
//  NAMING NOTES:
//    * Engine class `weather_mgr` is modeled here as `WeatherMgr`, `skybox` as
//      `Skybox`, `fog_plane` as `FogPlane`, and the nested `weather_mgr::fork`
//      as `LightningFork`, to keep PascalCase wrapper types distinct from the
//      forward-declared engine structs in meridian_types.h.
//    * Engine type names that collide with the std namespace would be written
//      global-qualified (::internal, ::system, ...) to stay correct under
//      `using namespace std;`. None are referenced by value here.
// ============================================================================
#pragma once

#include <cstdint>
#include "meridian_types.h"   // meridian::rebase + g_delta, vector3/radian3/bbox, xstring, property, xarray<T>, and weather_mgr/skybox/fog_plane/fork fwd-decls

// ---- Forward declarations for engine types we reference but don't model -----
// (Most are already declared globally in meridian_types.h; re-declaring a struct
//  name is harmless and keeps this header readable standalone.)
struct object;            // base returned by the *Creator factories
struct rigid_instance;    // base of skybox
struct wall;              // base of fog_plane
struct bin_in;            // OnImport stream
struct bin_out;           // OnExport stream
struct bitstream;         // Save/RestoreState stream
struct xcolor;            // RGBA color value (used by TriggerLightning by-ref)
struct property;          // complete in meridian_types.h (blob 0x258)

namespace weather_sdk {

// ===========================================================================
//  0. Constants recovered from the disassembly
// ===========================================================================

// weather_mgr::stateFlags @ weather_mgr+0x54
enum WeatherFlag : uint8_t {
    WEATHER_STORM_ACTIVE    = 0x01, // bit0  rain/storm intensity ramp active (set by EnableRain)
    WEATHER_PARTICLE_ACTIVE = 0x02, // bit1  particle-weather system active
};

// Misc magic constants used by the lightning/storm paths.
enum WeatherConst : uint32_t {
    WEATHER_LIGHTNING_TTL      = 0x1e,       // 30 frames: EnableStorm sets stormDuration(+0x88)
    WEATHER_DEFAULT_BOLT_COLOR = 0xffb4e6ff, // pale violet-white default bolt RGBA (TriggerLightningChain)
    WEATHER_PRIMARY_FORK_MAX   = 0x20,       // 32 primary forks  (GetUnusedPrimaryFork cap)
    WEATHER_SECONDARY_FORK_MAX = 0x200,      // 512 secondary forks (GetUnusedSecondaryFork cap)
};

// ===========================================================================
//  1. LightningFork — nested weather_mgr::fork (one bolt branch).
//     Allocated 0x14 bytes by GetUnused*Fork; a 0x45c-byte geometry block hangs
//     off +0x4 (segment vertex buffer). Cast a fork* to this.
// ===========================================================================
// The ctor (0x00551040) writes byte flags at +0x0d, +0x0f, +0x11, +0x13 and dwords
// at +0x4 / +0x8; the 0x45c geometry block holds the segment-count short at its +0x2
// and the vertex array (stride 0xc) referenced by RenderFork. textureA/textureB
// handles for RenderFork are read from the geometry block (+0xc/+0x10), not the
// fork header. Byte-flag meanings are partly inferred ("?").
#pragma pack(push, 1)
struct LightningFork {
    int16_t  lifetime;                 // 0x00  frames remaining (>0 = live); decremented in BuildFork
    uint8_t  _pad02[0x04 - 0x02];      // 0x02
    void*    geometry;                 // 0x04  -> 0x45c segment/geometry block (seg count short @ +0x2)
    void*    handle08;                 // 0x08  secondary geometry/buffer handle (freed by fork::Free) "?"
    uint8_t  _pad0c[0x0d - 0x0c];      // 0x0c
    uint8_t  flag0d;                   // 0x0d  flag byte (ctor = 0)
    uint8_t  _pad0e;                   // 0x0e
    uint8_t  alpha;                    // 0x0f  fade/alpha byte (ctor = 0xff; BuildFork writes __ftol(color.a))
    uint8_t  _pad10;                   // 0x10
    uint8_t  alpha11;                  // 0x11  secondary alpha byte (ctor = 0xff) "?"
    uint8_t  _pad12;                   // 0x12
    uint8_t  flag13;                   // 0x13  cleared (=0) each BuildFork update; ctor = 0xff
};                                     // size 0x14
#pragma pack(pop)

// ===========================================================================
//  2. WeatherMgr — global weather state singleton (engine weather_mgr).
//     The live instance is the engine global g_WeatherMgr; cast its address.
//     Do NOT instantiate.
// ===========================================================================
// stormEffectActive(0x58) is immediately followed by stormEffectBase(0x5c), so
// there is NO padding between them (the gap would be zero-length and is omitted).
#pragma pack(push, 1)
struct WeatherMgr {
    uint8_t  _pad000[0x10 - 0x00];     // 0x000  base/header (SetDefaults memclears 0x10 bytes)
    float    stormIntensity;           // 0x010  rain/storm intensity; fades when < 0.001
    float    rainEffectScale;          // 0x014  rain particle effect scale (default 1.0; Save/RestoreState)
    uint8_t  _pad018[0x50 - 0x18];     // 0x018
    void*    weatherSystemHandle;      // 0x050  particle-weather system handle (FUN_0065a050/FUN_00659c80)
    uint8_t  stateFlags;               // 0x054  WeatherFlag bitfield (bit0 storm, bit1 particle)
    uint8_t  _pad055[0x58 - 0x55];     // 0x055
    int32_t  stormEffectActive;        // 0x058  secondary storm-effect active flag (Save/RestoreState)
    float    stormEffectBase;          // 0x05c  base of the +0x5c..0x60 storm effect (FUN_005893e0)
    float    stormEffectScale;         // 0x060  storm-effect intensity (default 1.0; restored to 1.0)
    uint8_t  _pad064[0x6c - 0x64];     // 0x064
    int32_t  renderDrawCount;          // 0x06c  Render resets to 0 (accumulator)
    void*    stormRenderBuffer;        // 0x070  storm volume render buffer/handle (freed when slots==0)
    int32_t  stormRenderCount;         // 0x074  Render clamps to >= 10; storm-volume capacity target
    int32_t  stormActiveSlots;         // 0x078  active storm-volume slots (0 => free render buffer)
    uint8_t  _pad07c[0x84 - 0x7c];     // 0x07c
    int32_t  stormEffectSelector;      // 0x084  storm/ambient effect active selector (Save/RestoreState)
    int32_t  lightningTtl;             // 0x088  lightning-flash lifetime; PreSceneRender counts down
    void*    lightningEffectHandle;    // 0x08c  EnableStorm: FUN_00647b10(0,6) effect handle
    float    lightningRadius;          // 0x090  EnableStorm sets 2.0 (also base of FUN_005893e0)
    vector3  stormCenter;              // 0x094  storm world position (EnableStorm copies param center)
    uint8_t  stormColor[4];            // 0x0a0  storm RGBA tint (EnableStorm copies param color)
    uint8_t  _pad0a4[0xa8 - 0xa4];     // 0x0a4
    uint8_t  forkCount;                // 0x0a8  primary fork count (BuildFork loop bound)
    uint8_t  secondaryForkCount;       // 0x0a9  secondary fork count (GetUnusedSecondaryFork cap)
    uint8_t  _pad0aa[0xac - 0xaa];     // 0x0aa
    void**   forks;                    // 0x0ac  primary fork pointer array (0x80 bytes = 32 ptrs)
    void**   secondaryForks;           // 0x0b0  secondary fork pointer array (0x800 bytes = 512 ptrs)
};                                     // size >= 0xb4 (singleton; trailing fields beyond 0xb4 unmapped)
#pragma pack(pop)

// ===========================================================================
//  3. Skybox — sky-dome object (engine skybox, derives from rigid_instance).
//     sizeof == 0x188 (SkyboxCreator operator_new(0x188)). Cast a slot pointer.
// ===========================================================================
#pragma pack(push, 1)
struct Skybox {
    void*    vtable;                   // 0x000  &PTR_FUN_006eebf8
    uint8_t  _pad004[0x82 - 0x04];     // 0x004  object / rigid_instance region
    uint8_t  tintB;                    // 0x082  tint blue   (Init = 0xff)
    uint8_t  tintG;                    // 0x083  tint green  (Init = 0xff)
    uint8_t  tintR;                    // 0x084  tint red    (Init = 0xff)
    uint8_t  tintA;                    // 0x085  tint alpha  (Init = 0xff) -> opaque white
    uint8_t  _pad086[0x160 - 0x86];    // 0x086
    vector3  offsetScale;              // 0x160  "OffsetScale" / editor "Offset Scaling"
    float    animSpeed;                // 0x16c  "AnimSpeed"  / editor "Anim Speed"
    vector3  center;                   // 0x170  "Center"
    uint8_t  _pad17c[0x188 - 0x17c];   // 0x17c  (trailing dwords zeroed by ctor)
};                                     // size 0x188
#pragma pack(pop)

// ===========================================================================
//  4. FogPlane — planar/distance fog quad (engine fog_plane, derives from wall).
//     sizeof == 0x290 (FogPlaneCreator operator_new(0x290)). Cast a slot pointer.
// ===========================================================================
#pragma pack(push, 1)
struct FogPlane {
    void*    vtable;                   // 0x000  &PTR_FUN_006ed1b8
    uint8_t  _pad004[0x158 - 0x04];    // 0x004  object / wall region
    void*    fogTextureA;              // 0x158  "FogTextureA" texture handle
    void*    fogTextureB;              // 0x15c  "FogTextureB" texture handle
    void*    maskTexture;              // 0x160  "MaskTexture" texture handle (also editor-enum default region "?")
    // Vert0..Vert3 are four contiguous vector3 corners (12 bytes each, no gaps).
    vector3  vert0;                    // 0x164  "Vert0" corner
    vector3  vert1;                    // 0x170  "Vert1" corner
    vector3  vert2;                    // 0x17c  "Vert2" corner
    vector3  vert3;                    // 0x188  "Vert3" corner
    uint8_t  _pad194[0x248 - 0x194];   // 0x194  (blend-mode enum + misc state)
    // 0x248  animated layer block: per-layer Layer%d UTile/VTile/UScroll/VScroll/
    //        UAmp/VAmp/UFreq... floats (stride 0x8 per parameter in the import loop).
    uint8_t  layers[0x290 - 0x248];    // 0x248  animated UV-scroll layer params
};                                     // size 0x290
#pragma pack(pop)

// ===========================================================================
//  5. Singleton / factory address accessors
// ===========================================================================
// The engine weather manager is a process-global singleton living AT this .data
// address (g_WeatherMgr). CONFIRMED: weather_mgr::Init and weather_mgr::Kill load
// it as `mov ecx, 0x00771B70`, and the decompiler types the calls in
// OnAdvanceLogic / Render / EnableStorm as (weather_mgr*)&DAT_00771b70.
// The object is embedded at the address (it is NOT a pointer stored there), so
// the WeatherMgr* IS the rebased address.
#define WEATHER_MGR_VA 0x00771b70

// Raw address of the global weather_mgr instance (rebased for the live module).
inline void* g_WeatherMgr_at() { return meridian::rebase(WEATHER_MGR_VA); }

// Convenience: the live weather manager singleton, ready to pass to fn::WeatherMgr_*.
//   WeatherMgr* wm = weather_sdk::GetWeatherMgr();
//   weather_sdk::fn::WeatherMgr_EnableRain(wm, 1, 1.0f);
inline WeatherMgr* GetWeatherMgr() {
    return reinterpret_cast<WeatherMgr*>(meridian::rebase(WEATHER_MGR_VA));
}

// object* __cdecl SkyboxCreator(void)  — operator_new(0x188) + skybox ctor.
inline void* SkyboxCreator_at()   { return meridian::rebase(0x004ce020); }
// object* __cdecl FogPlaneCreator(void) — operator_new(0x290) + fog_plane ctor.
inline void* FogPlaneCreator_at() { return meridian::rebase(0x00481440); }

// ===========================================================================
//  6. Typed call wrappers
//     __thiscall: object pointer is the FIRST argument.
// ===========================================================================
namespace fn {

// ---- WeatherMgr: lifecycle -------------------------------------------------
// weather_mgr::Init(void) — reset render accumulators, then SetDefaults.
inline void WeatherMgr_Init(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x005510b0))(wm);
}
// weather_mgr::SetDefaults(void) — intensities=1.0, clear flags & fork pools.
inline void WeatherMgr_SetDefaults(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x00551130))(wm);
}
// weather_mgr::Kill(void) — stop particle weather, free both fork pools + render buffer.
inline void WeatherMgr_Kill(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x00551190))(wm);
}

// ---- WeatherMgr: weather state ---------------------------------------------
// weather_mgr::EnableRain(int enable, float fade) — start/stop "RainOutdoorLoop"
//   + particle weather; sets stateFlags bit0 (and bit1) and ramps the rain effect.
//   `enable`: non-zero = rain on, 0 = rain off.  `fade`: ramp time in seconds.
//   The rain *intensity* itself is the field rainEffectScale (WeatherMgr+0x14).
//   Verified arg layout: ret 8 = exactly 2 stack args (do NOT pass a 3rd).
inline void WeatherMgr_EnableRain(WeatherMgr* wm, int enable, float fade) {
    using F = void(__thiscall*)(WeatherMgr*, int, float);
    reinterpret_cast<F>(meridian::rebase(0x00551280))(wm, enable, fade);
}
// weather_mgr::EnableStorm(const vector3* center, const uint8_t color[4]) — ignite a
//   localized lightning storm at `center` with RGBA `color`; plays "LightningCrack".
//   (Demangled sig is (int,float) but both args are pointers in the body.)
inline void WeatherMgr_EnableStorm(WeatherMgr* wm, const vector3* center, const uint8_t color[4]) {
    using F = void(__thiscall*)(WeatherMgr*, const vector3*, const uint8_t*);
    reinterpret_cast<F>(meridian::rebase(0x005513a0))(wm, center, color);
}

// ---- WeatherMgr: lightning -------------------------------------------------
// weather_mgr::TriggerLightningChain(from, to, strength, branchy, unused) -> forkIdx
//   (5-arg overload). Computes width/taper from bolt length, default bolt color,
//   then forwards to the 10-arg core. Returns the fork index (or -1).
inline int WeatherMgr_TriggerLightningChain(WeatherMgr* wm, const vector3& from, const vector3& to,
                                            float strength, int branchy, int unused) {
    using F = int(__thiscall*)(WeatherMgr*, const vector3&, const vector3&, float, int, int);
    return reinterpret_cast<F>(meridian::rebase(0x00551460))(wm, from, to, strength, branchy, unused);
}
// weather_mgr::TriggerLightningChain (10-arg core) -> forkIdx
//   Raw sig: int __thiscall(weather_mgr*, const vector3& from, const vector3& to,
//            float width, float taper, float a, float b, int segs, float jitter,
//            const xcolor& color, int branchy)
//   xcolor is incomplete here (passed by const&), so a by-ref typed wrapper is used.
inline int WeatherMgr_TriggerLightningChainEx(WeatherMgr* wm, const vector3& from, const vector3& to,
                                              float width, float taper, float a, float b, int segs,
                                              float jitter, const xcolor& color, int branchy) {
    using F = int(__thiscall*)(WeatherMgr*, const vector3&, const vector3&, float, float, float,
                               float, int, float, const xcolor&, int);
    return reinterpret_cast<F>(meridian::rebase(0x00551520))(wm, from, to, width, taper, a, b, segs,
                                                             jitter, color, branchy);
}
// protected weather_mgr::SplitFork(vector3* pts, int lo, int hi, float jitter)
//   Recursive midpoint-displacement fractal subdivision of one bolt's polyline.
inline void WeatherMgr_SplitFork(WeatherMgr* wm, vector3* pts, int lo, int hi, float jitter) {
    using F = void(__thiscall*)(WeatherMgr*, vector3*, int, int, float);
    reinterpret_cast<F>(meridian::rebase(0x00552890))(wm, pts, lo, hi, jitter);
}
// protected weather_mgr::GetUnusedPrimaryFork(fork** out) -> index
inline int WeatherMgr_GetUnusedPrimaryFork(WeatherMgr* wm, void** out) {
    using F = int(__thiscall*)(WeatherMgr*, void**);
    return reinterpret_cast<F>(meridian::rebase(0x005522c0))(wm, out);
}
// protected weather_mgr::GetUnusedSecondaryFork(int bucket) -> fork*
inline void* WeatherMgr_GetUnusedSecondaryFork(WeatherMgr* wm, int bucket) {
    using F = void*(__thiscall*)(WeatherMgr*, int);
    return reinterpret_cast<F>(meridian::rebase(0x005523d0))(wm, bucket);
}

// ---- WeatherMgr: per-frame render ------------------------------------------
// weather_mgr::OnAdvanceLogic(float dt) — main per-frame weather tick.
inline void WeatherMgr_OnAdvanceLogic(WeatherMgr* wm, float dt) {
    using F = void(__thiscall*)(WeatherMgr*, float);
    reinterpret_cast<F>(meridian::rebase(0x00551c20))(wm, dt);
}
// weather_mgr::PreSceneRender(void) — strobe the lightning flash light this frame.
inline void WeatherMgr_PreSceneRender(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x00551980))(wm);
}
// weather_mgr::RenderLightningForks(void) — gate, then (re)build live forks.
inline void WeatherMgr_RenderLightningForks(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x005519f0))(wm);
}
// weather_mgr::Render(void) — scan "Storm_" UI markers, submit storm volumes.
inline void WeatherMgr_Render(WeatherMgr* wm) {
    using F = void(__thiscall*)(WeatherMgr*);
    reinterpret_cast<F>(meridian::rebase(0x00551a80))(wm);
}
// protected weather_mgr::BuildFork(fork* fk, int isPrimary, const vector3& from,
//   const vector3& to, float jitter, float taper, float width) — per-frame fork
//   lifetime tick + re-emit; gated by the "Lightning Forks" cvar.
inline void WeatherMgr_BuildFork(WeatherMgr* wm, void* fk, int isPrimary, const vector3& from,
                                 const vector3& to, float jitter, float taper, float width) {
    using F = void(__thiscall*)(WeatherMgr*, void*, int, const vector3&, const vector3&,
                                float, float, float);
    reinterpret_cast<F>(meridian::rebase(0x00552af0))(wm, fk, isPrimary, from, to, jitter, taper, width);
}

// ---- WeatherMgr: save / load -----------------------------------------------
// weather_mgr::SaveState(bitstream& bs) — serialize active flags + intensities.
inline void WeatherMgr_SaveState(WeatherMgr* wm, bitstream* bs) {
    using F = void(__thiscall*)(WeatherMgr*, bitstream*);
    reinterpret_cast<F>(meridian::rebase(0x00552e30))(wm, bs);
}
// weather_mgr::RestoreState(bitstream& bs) — mirror of SaveState.
inline void WeatherMgr_RestoreState(WeatherMgr* wm, bitstream* bs) {
    using F = void(__thiscall*)(WeatherMgr*, bitstream*);
    reinterpret_cast<F>(meridian::rebase(0x00552ea0))(wm, bs);
}

// ---- LightningFork helpers -------------------------------------------------
// weather_mgr::fork ctor — zero/default a freshly allocated fork (0x14 bytes).
inline void LightningFork_ctor(LightningFork* fk) {
    using F = void(__thiscall*)(LightningFork*);
    reinterpret_cast<F>(meridian::rebase(0x00551040))(fk);
}
// weather_mgr::fork free/reset — release geometry handle, reset fields.
inline void LightningFork_Free(LightningFork* fk) {
    using F = void(__thiscall*)(LightningFork*);
    reinterpret_cast<F>(meridian::rebase(0x00551070))(fk);
}

// ---- Skybox ----------------------------------------------------------------
// skybox::Init(const vector3& pos, const radian3& rot, const vector3& scale, const bbox& box)
//   — construct/configure: opaque-white tint, background render priority, no collision.
inline void Skybox_Init(Skybox* sky, const vector3& pos, const radian3& rot,
                        const vector3& scale, const bbox& box) {
    using F = void(__thiscall*)(Skybox*, const vector3&, const radian3&, const vector3&, const bbox&);
    reinterpret_cast<F>(meridian::rebase(0x004ce0e0))(sky, pos, rot, scale, box);
}
// skybox ctor — rigid_instance base + install skybox vtable.
inline void Skybox_ctor(Skybox* sky) {
    using F = void(__thiscall*)(Skybox*);
    reinterpret_cast<F>(meridian::rebase(0x004ce080))(sky);
}
// virtual skybox::OnAdvanceLogic(float dt) — scroll/animate the dome.
inline void Skybox_OnAdvanceLogic(Skybox* sky, float dt) {
    using F = void(__thiscall*)(Skybox*, float);
    reinterpret_cast<F>(meridian::rebase(0x004ce250))(sky, dt);
}
// virtual skybox::OnImport(bin_in&) — read OffsetScale/Center/AnimSpeed; disable collision.
inline void Skybox_OnImport(Skybox* sky, bin_in* s) {
    using F = void(__thiscall*)(Skybox*, bin_in*);
    reinterpret_cast<F>(meridian::rebase(0x004ce630))(sky, s);
}
// virtual skybox::OnExport(bin_out&) — write OffsetScale/Center/AnimSpeed.
inline void Skybox_OnExport(Skybox* sky, bin_out* s) {
    using F = void(__thiscall*)(Skybox*, bin_out*);
    reinterpret_cast<F>(meridian::rebase(0x004ce5e0))(sky, s);
}
// virtual skybox::SetProperty(const char* name, const property& val) -> int
inline int Skybox_SetProperty(Skybox* sky, const char* name, const property& val) {
    using F = int(__thiscall*)(Skybox*, const char*, const property&);
    return reinterpret_cast<F>(meridian::rebase(0x004ce9f0))(sky, name, val);
}
// virtual skybox::`scalar deleting destructor'(unsigned int flags)
inline void* Skybox_scalar_deleting_dtor(Skybox* sky, unsigned int flags) {
    using F = void*(__thiscall*)(Skybox*, unsigned int);
    return reinterpret_cast<F>(meridian::rebase(0x004ce0a0))(sky, flags);
}

// ---- FogPlane --------------------------------------------------------------
// fog_plane ctor — wall base + install fog_plane vtable + default empty textures.
inline void FogPlane_ctor(FogPlane* fp) {
    using F = void(__thiscall*)(FogPlane*);
    reinterpret_cast<F>(meridian::rebase(0x004814a0))(fp);
}
// virtual fog_plane::OnAdvanceLogic(float dt) — advance per-layer UV scroll phase.
inline void FogPlane_OnAdvanceLogic(FogPlane* fp, float dt) {
    using F = void(__thiscall*)(FogPlane*, float);
    reinterpret_cast<F>(meridian::rebase(0x00481990))(fp, dt);
}
// virtual fog_plane::RenderCustom(void) — draw the textured, UV-scrolling fog quad.
inline void FogPlane_RenderCustom(FogPlane* fp) {
    using F = void(__thiscall*)(FogPlane*);
    reinterpret_cast<F>(meridian::rebase(0x00483d30))(fp);
}
// virtual fog_plane::OnImport(bin_in&) — read textures, Vert0..3, animated layers.
inline void FogPlane_OnImport(FogPlane* fp, bin_in* s) {
    using F = void(__thiscall*)(FogPlane*, bin_in*);
    reinterpret_cast<F>(meridian::rebase(0x00481f90))(fp, s);
}
// virtual fog_plane::OnExport(bin_out&) — mirror of OnImport.
inline void FogPlane_OnExport(FogPlane* fp, bin_out* s) {
    using F = void(__thiscall*)(FogPlane*, bin_out*);
    reinterpret_cast<F>(meridian::rebase(0x00481b90))(fp, s);
}
// virtual fog_plane::EnumerateProperties(xarray<property_desc>&)
//   Raw sig: void __thiscall fog_plane::EnumerateProperties(fog_plane*, xarray<property_desc>&)
inline void FogPlane_EnumerateProperties(FogPlane* fp, xarray<property_desc>* out) {
    using F = void(__thiscall*)(FogPlane*, xarray<property_desc>*);
    reinterpret_cast<F>(meridian::rebase(0x00483400))(fp, out);
}
// virtual fog_plane::`scalar deleting destructor'(unsigned int flags)
inline void* FogPlane_scalar_deleting_dtor(FogPlane* fp, unsigned int flags) {
    using F = void*(__thiscall*)(FogPlane*, unsigned int);
    return reinterpret_cast<F>(meridian::rebase(0x004816e0))(fp, flags);
}

} // namespace fn

} // namespace weather_sdk
